module:
  mounts:
    - source: blocks
      target: layouts/partials/blocks/
      includeFiles: '**.html'
    - source: blocks
      target: layouts/partials/blocks/
      includeFiles: '**.scss'
imports:
    - path: github.com/SpongeBaby1/wowchemy-block-jimingwu
